### ISSUE TITLE
Не знаю почему это не работает

### ISSUE THREAD

**Issue by Sch1257** [Sch1257/test#1]
a = int()
print(a)

Почему это не работает

**Comment by Sch1257** [comment]
Ты дурак

**Comment by nobody-forever** [comment]
a = input()
print(a)

Должно работать :D

**Comment by Sch1257** [comment]
Спасибо за помощь

**Comment by nobody-forever** [comment]
> Спасибо за помощь

Пожалуйста)
А рассказать про полиморфизм , инкапсуляцию и асбтракцию устно можно будет?
